#
# Common configuration for each firstwiki repo
#

permalink:        pretty

exclude: [vendor, script]

gems:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-github-metadata
  
author:
  name:           FIRSTWiki Contributors
  url:            http://firstwiki.github.io
  email:

# Setup
title:            FIRSTwiki
tagline:          The FIRST Robotics encyclopedia
paginate:         5
safe:             false
excerpt_separator: ""
strict_front_matter: true

data_dir:         _common/_data
includes_dir:     _common/_includes
layouts_dir:      _common/_layouts

#
# Begin specific configuration for this repo
#

url:              http://firstwiki.github.io
baseurl:          /wiki

collections:
  history:
    output: true
    permalink: /:slug
  main: 
    output: true
    permalink: /:slug
  nontech:
    output: true
    permalink: /:slug
  people:
    output: true
    permalink: /:slug
  tech:
    output: true
    permalink: /:slug

#
# Defaults to make it easy to contribute new content
#

defaults:
  - 
    scope:
      path: ""
      type: "history"
    values:
      layout: page
  - 
    scope:
      path: ""
      type: "main"
    values:
      layout: page
  - 
    scope:
      path: ""
      type: "nontech"
    values:
      layout: page
  - 
    scope:
      path: ""
      type: "people"
    values:
      layout: page
  - 
    scope:
      path: ""
      type: "tech"
    values:
      layout: page
